<?php


/**
 * Implements hook_node_view().
 */

function node_viewcount_node_view($node, $view_mode, $langcode) {
global $user;
  if ($view_mode == 'full' && $node->type == 'community_lifeecho' && $node->uid == $user->uid ) {

  $num = node_viewcount_select_count($node->nid, $user->uid);
  if($num == 0) {
  node_viewcount_count_view_insert($node->nid, $user->uid);
  }
  else {
  node_viewcount_count_view_update($node->nid, $user->uid);
  }

  }

}

function node_viewcount_count_view_insert($nid, $uid) {
  $fields = array(
    'nid' => $nid,  
    'uid' => $uid,
    'timestamp' => REQUEST_TIME,
  );
  return drupal_write_record('node_viewcount', $fields);
}

function node_viewcount_count_view_update($nid, $uid) {

$query = db_update('node_viewcount');
$query->fields(array('status' => 1));
$query->condition('nid', $nid, '=');
$query->condition('uid', $uid, '=');
$result = $query->execute();

}

function node_viewcount_count_view_select($nid, $uid) {
  $query = db_select('node_viewcount', 'nvc');
  $query->fields('nvc', array('nid'));  
  $query->condition('nid', $nid, '=');
  $query->condition('uid', $uid, '=');
  $query->condition('status', 0 , '=');
  $result = $query->execute();
  $rowcount = $result->rowCount();
  return $rowcount;
}

function node_viewcount_select_count($nid, $uid) {
  $query = db_select('node_viewcount', 'nvc');
  $query->fields('nvc', array('nid'));  
  $query->condition('nid', $nid, '=');
  $query->condition('uid', $uid, '=');
  $result = $query->execute();
  $rowcount = $result->rowCount();
  return $rowcount;
}
