<?php
/**
* Implementation of hook_menu().
*/


function TransNationalPayment_menu() {
	
	$items['admin/config/TransNationalPayment'] = array(
	'title' => 'TransNational Payment configuration',
	'description' => 'TransNationalPayment.',
	'position' => 'right',
	'weight' => -5,
	'page callback' => 'system_admin_menu_block_page',
	'access arguments' => array('administer site configuration'),
	'file' => 'system.admin.inc',
	'file path' => drupal_get_path('module', 'system'),
	);
	
	
	$items['admin/config/TransNationalPayment/settings'] = array(
	'title' => 'TransNationalPayment settings',
	'description' => 'TransNational Payment settings',
	'page callback' => 'drupal_get_form',
	'page arguments' => array('TransNationalPayment_admin_settings'),
	'access arguments' => array('administer site configuration'),
	'type' => MENU_NORMAL_ITEM,
	'file' => 'TransNationalPayment.admin.inc',
	);
	
	return $items;
	}

	
	
?>